// The ending cutscene's timeline. Generated by tools/make_ending_scene.py
// alongside assets/sprites/ending_scene.png and ending_knight.png: change
// the tool and run it again rather than editing this by hand.
#pragma once

#include "CutsceneStep.h"

namespace EndingTable {

constexpr int FRAME_W = 128;
constexpr int FRAME_H = 72;
constexpr int COLUMNS = 16;    // frames per row of the sheet

// The knight is drawn over the scene in whatever he finished wearing, from
// ending_knight.png: a row per light, and in each row every armour tier then
// every weapon tier, POSES frames each. A step's `knight` is light * POSES + pose.
constexpr int KNIGHT_X = 13;   // his frame's top left, in scene pixels
constexpr int KNIGHT_Y = 26;
constexpr int KNIGHT_W = 30;
constexpr int KNIGHT_H = 32;
constexpr int TIERS = 9;
constexpr int POSES = 2;
constexpr int LIGHTS = 5;

constexpr CutsceneStep STEPS[] = {
    { 0, 160, nullptr, 0 }, { 1, 160, nullptr, 0 }, { 2, 160, nullptr, 0 }, { 3, 160, nullptr, 1 },
    { 4, 160, nullptr, 1 }, { 5, 160, nullptr, 1 }, { 6, 160, nullptr, 0 }, { 7, 160, nullptr, 0 },
    { 8, 160, nullptr, 0 }, { 9, 160, nullptr, 1 }, { 10, 160, nullptr, 1 }, { 11, 160, nullptr, 1 },
    { 12, 160, nullptr, 0 }, { 13, 160, nullptr, 0 }, { 14, 200, nullptr, 0 }, { 15, 200, nullptr, 1 },
    { 16, 240, nullptr, 0 }, { 17, 240, nullptr, 0 }, { 14, 240, nullptr, 0 }, { 15, 240, nullptr, 1 },
    { 18, 240, nullptr, 1 }, { 19, 240, nullptr, 1 }, { 20, 200, nullptr, 0 }, { 21, 200, nullptr, 0 },
    { 22, 200, nullptr, 0 }, { 23, 200, nullptr, 1 }, { 24, 200, nullptr, 1 }, { 25, 200, nullptr, 3 },
    { 26, 200, nullptr, 2 }, { 27, 200, nullptr, 2 }, { 28, 200, nullptr, 2 }, { 29, 200, nullptr, 3 },
    { 30, 200, nullptr, 3 }, { 31, 200, nullptr, 3 }, { 32, 200, nullptr, 2 }, { 33, 200, nullptr, 2 },
    { 34, 240, nullptr, 2 }, { 33, 240, nullptr, 2 }, { 35, 240, nullptr, 2 }, { 36, 240, nullptr, 3 },
    { 37, 240, nullptr, 3 }, { 38, 240, nullptr, 3 }, { 39, 200, nullptr, 2 }, { 40, 200, nullptr, 2 },
    { 41, 200, nullptr, 2 }, { 42, 200, nullptr, 5 }, { 43, 200, nullptr, 5 }, { 44, 200, nullptr, 5 },
    { 45, 200, nullptr, 4 }, { 46, 200, nullptr, 4 }, { 47, 200, nullptr, 6 }, { 48, 200, nullptr, 7 },
    { 49, 200, nullptr, 7 }, { 50, 200, nullptr, 7 }, { 51, 200, nullptr, 8 }, { 52, 200, nullptr, 8 },
    { 53, 200, nullptr, 8 }, { 54, 200, nullptr, 9 }, { 55, 240, nullptr, 8 }, { 56, 240, nullptr, 8 },
    { 57, 240, nullptr, 8 }, { 54, 240, nullptr, 9 }, { 58, 240, nullptr, 9 }, { 59, 240, nullptr, 9 },
    { 55, 240, nullptr, 8 }, { 56, 240, nullptr, 8 }, { 57, 240, nullptr, 8 }, { 54, 240, nullptr, 9 },
    { 58, 240, nullptr, 9 }, { 59, 240, nullptr, 9 },
};

// One shot per line of the ending, in order; the last holds under the banner.
constexpr int SHOTS = 4;
constexpr CutsceneShot SHOT[SHOTS] = {
    { 0, 16, 6 },
    { 22, 14, 6 },
    { 42, 16, 6 },
    { 64, 0, 6 },
};

} // namespace EndingTable
