// The opening cutscene's timeline. Generated by tools/make_intro_scene.py
// alongside assets/sprites/intro_scene.png: change the tool and run it
// again rather than editing this by hand.
#pragma once

#include "CutsceneStep.h"

namespace IntroTable {

constexpr int FRAME_W = 128;
constexpr int FRAME_H = 72;
constexpr int COLUMNS = 16;    // frames per row of the sheet

constexpr CutsceneStep STEPS[] = {
    { 0, 240, nullptr, -1 }, { 1, 240, nullptr, -1 }, { 2, 240, nullptr, -1 }, { 3, 240, nullptr, -1 },
    { 4, 240, nullptr, -1 }, { 5, 240, nullptr, -1 }, { 6, 170, nullptr, -1 }, { 7, 170, nullptr, -1 },
    { 8, 170, nullptr, -1 }, { 9, 170, nullptr, -1 }, { 10, 170, nullptr, -1 }, { 11, 170, nullptr, -1 },
    { 12, 170, nullptr, -1 }, { 13, 170, nullptr, -1 }, { 14, 170, nullptr, -1 }, { 15, 170, nullptr, -1 },
    { 16, 170, nullptr, -1 }, { 17, 170, nullptr, -1 }, { 18, 170, nullptr, -1 }, { 19, 170, nullptr, -1 },
    { 20, 240, nullptr, -1 }, { 19, 240, nullptr, -1 }, { 21, 240, nullptr, -1 }, { 22, 240, nullptr, -1 },
    { 23, 240, nullptr, -1 }, { 24, 240, nullptr, -1 }, { 25, 150, nullptr, -1 }, { 26, 150, nullptr, -1 },
    { 27, 150, nullptr, -1 }, { 28, 150, nullptr, -1 }, { 29, 150, nullptr, -1 }, { 30, 380, nullptr, -1 },
    { 31, 110, nullptr, -1 }, { 32, 110, nullptr, -1 }, { 33, 110, nullptr, -1 }, { 34, 110, nullptr, -1 },
    { 35, 110, nullptr, -1 }, { 36, 110, nullptr, -1 }, { 37, 110, nullptr, -1 }, { 38, 110, nullptr, -1 },
    { 39, 120, nullptr, -1 }, { 40, 120, nullptr, -1 }, { 41, 120, nullptr, -1 }, { 42, 120, nullptr, -1 },
    { 43, 120, nullptr, -1 }, { 44, 120, nullptr, -1 }, { 45, 120, nullptr, -1 }, { 46, 100, nullptr, -1 },
    { 47, 100, nullptr, -1 }, { 48, 100, nullptr, -1 }, { 49, 100, nullptr, -1 }, { 50, 100, nullptr, -1 },
    { 51, 150, nullptr, -1 }, { 52, 220, nullptr, -1 }, { 53, 120, nullptr, -1 }, { 54, 110, nullptr, -1 },
    { 55, 100, nullptr, -1 }, { 56, 170, "defend", -1 }, { 57, 220, nullptr, -1 }, { 58, 240, nullptr, -1 },
    { 59, 240, nullptr, -1 }, { 60, 240, nullptr, -1 }, { 61, 240, nullptr, -1 }, { 62, 240, nullptr, -1 },
    { 63, 240, nullptr, -1 }, { 64, 90, nullptr, -1 }, { 65, 90, nullptr, -1 }, { 66, 90, nullptr, -1 },
    { 67, 90, nullptr, -1 }, { 68, 90, nullptr, -1 }, { 69, 90, nullptr, -1 }, { 70, 90, nullptr, -1 },
    { 71, 90, nullptr, -1 }, { 72, 90, nullptr, -1 }, { 73, 90, nullptr, -1 }, { 74, 110, nullptr, -1 },
    { 75, 110, nullptr, -1 }, { 76, 170, nullptr, -1 }, { 77, 110, nullptr, -1 }, { 78, 110, nullptr, -1 },
    { 79, 110, nullptr, -1 }, { 80, 110, nullptr, -1 }, { 81, 110, nullptr, -1 }, { 82, 120, nullptr, -1 },
    { 83, 120, nullptr, -1 }, { 84, 120, nullptr, -1 }, { 85, 240, nullptr, -1 }, { 86, 240, nullptr, -1 },
    { 87, 240, nullptr, -1 }, { 88, 240, nullptr, -1 }, { 89, 240, nullptr, -1 }, { 90, 240, nullptr, -1 },
    { 91, 150, nullptr, -1 }, { 92, 150, nullptr, -1 }, { 93, 150, nullptr, -1 }, { 94, 150, nullptr, -1 },
    { 95, 150, nullptr, -1 }, { 96, 150, nullptr, -1 }, { 97, 150, nullptr, -1 }, { 98, 150, nullptr, -1 },
    { 99, 150, nullptr, -1 }, { 100, 150, nullptr, -1 }, { 101, 240, nullptr, -1 }, { 102, 240, nullptr, -1 },
    { 103, 240, nullptr, -1 }, { 100, 240, nullptr, -1 }, { 104, 240, nullptr, -1 }, { 105, 240, nullptr, -1 },
    { 106, 140, nullptr, -1 }, { 107, 140, nullptr, -1 }, { 108, 140, nullptr, -1 }, { 109, 140, nullptr, -1 },
    { 110, 140, nullptr, -1 }, { 111, 140, nullptr, -1 }, { 112, 140, nullptr, -1 }, { 113, 520, nullptr, -1 },
    { 114, 240, nullptr, -1 }, { 115, 240, nullptr, -1 }, { 116, 240, nullptr, -1 }, { 117, 240, nullptr, -1 },
    { 118, 240, nullptr, -1 }, { 119, 240, nullptr, -1 },
};

// One shot per line of the intro, in order.
constexpr int SHOTS = 6;
constexpr CutsceneShot SHOT[SHOTS] = {
    { 0, 0, 6 },
    { 6, 14, 6 },
    { 26, 33, 6 },
    { 65, 21, 6 },
    { 92, 10, 6 },
    { 108, 8, 6 },
};

} // namespace IntroTable
